export const zabarAudio = {
  maaa: require("../../assets/audio/zabar/2harf/maaa.m4a"),
  laka: require("../../assets/audio/zabar/2harf/laka.m4a"),
  saja: require("../../assets/audio/zabar/2harf/saja.m4a"),
  tara: require("../../assets/audio/zabar/2harf/tara.m4a"),
  faaa: require("../../assets/audio/zabar/2harf/faaa.m4a"),
  nafa: require("../../assets/audio/zabar/2harf/nafa.m4a"),
  waaa: require("../../assets/audio/zabar/2harf/waaa.m4a"),
  faja: require("../../assets/audio/zabar/2harf/faja.m4a"),
  aala: require("../../assets/audio/zabar/2harf/alaa.m4a"),
  aama: require("../../assets/audio/zabar/2harf/aama.m4a"),
  mana: require("../../assets/audio/zabar/2harf/mana.m4a"),
  aaha: require("../../assets/audio/zabar/2harf/aaha.m4a"),
  swama: require("../../assets/audio/zabar/2harf/swama.m4a"),

  // 4harf
  faqadara: require("../../assets/audio/harkaat/zabar/4harf/faqadara.m4a"),
  wazakara: require("../../assets/audio/harkaat/zabar/4harf/wazakara.m4a"),
  wajadaka: require("../../assets/audio/harkaat/zabar/4harf/wajadaka.m4a"),
  khalaqaka: require("../../assets/audio/harkaat/zabar/4harf/khalaqaka.m4a"),
  adalaka: require("../../assets/audio/harkaat/zabar/4harf/adalaka.m4a"),
  fajala: require("../../assets/audio/harkaat/zabar/4harf/fajala.m4a"),
  aaqabata: require("../../assets/audio/harkaat/zabar/4harf/aaqabata.m4a"),
  fahashara: require("../../assets/audio/harkaat/zabar/4harf/fahashara.m4a"),
  fantar: require("../../assets/audio/harkaat/zabar/4harf/fantar.m4a"),
  wakafara: require("../../assets/audio/harkaat/zabar/4harf/wakafara.m4a"),
  lazahaba: require("../../assets/audio/harkaat/zabar/4harf/lazahaba.m4a"),
  fabasa: require("../../assets/audio/harkaat/zabar/4harf/fabasa.m4a"),
  fagafara: require("../../assets/audio/harkaat/zabar/4harf/fagafara.m4a"),
  fasajada: require("../../assets/audio/harkaat/zabar/4harf/fasajada.m4a"),
} as const;
