export const basicLettersAudio = {
  baa: require('../../assets/audio/letters/baa.m4a'),
  taa: require('../../assets/audio/letters/taa.m4a'),
  saa: require('../../assets/audio/letters/saa.m4a'),
  nun: require('../../assets/audio/letters/nun.m4a'),
  yaa: require('../../assets/audio/letters/yaa.m4a'),
  laam: require('../../assets/audio/letters/laam.m4a'),
  jeem: require('../../assets/audio/letters/jeem.m4a'),
  haa: require('../../assets/audio/letters/haa.m4a'),
  khaa: require('../../assets/audio/letters/khaa.m4a'),
  seen: require('../../assets/audio/letters/seen.m4a'),
  sheen: require('../../assets/audio/letters/sheen.m4a'),
  swaad: require('../../assets/audio/letters/swaad.m4a'),
  dwaad: require('../../assets/audio/letters/dwaad.m4a'),
  aeen: require('../../assets/audio/letters/aeen.m4a'),
  gwaeen: require('../../assets/audio/letters/gwaeen.m4a'),
  faa: require('../../assets/audio/letters/faa.m4a'),
  qaaf: require('../../assets/audio/letters/qaaf.m4a'),
  kaaf: require('../../assets/audio/letters/kaaf.m4a'),
  meem: require('../../assets/audio/letters/meem.m4a'),
  s_haa: require('../../assets/audio/letters/s_haa.m4a'),
  hamzah: require('../../assets/audio/letters/hamzah.m4a'),
} as const;
