export const lettersAudio = {
  baa: require('../assets/audio/letters/baa.m4a'),
  taa: require('../assets/audio/letters/taa.m4a'),
  saa: require('../assets/audio/letters/saa.m4a'),
  nun: require('../assets/audio/letters/nun.m4a'),
  yaa: require('../assets/audio/letters/yaa.m4a'),
  laam: require('../assets/audio/letters/laam.m4a'),
  jeem: require('../assets/audio/letters/jeem.m4a'),
  haa: require('../assets/audio/letters/haa.m4a'),
  khaa: require('../assets/audio/letters/khaa.m4a'),
  seen: require('../assets/audio/letters/seen.m4a'),
  sheen: require('../assets/audio/letters/sheen.m4a'),
  swaad: require('../assets/audio/letters/swaad.m4a'),
  dwaad: require('../assets/audio/letters/dwaad.m4a'),
  aeen: require('../assets/audio/letters/aeen.m4a'),
  gwaeen: require('../assets/audio/letters/gwaeen.m4a'),
  faa: require('../assets/audio/letters/faa.m4a'),
  qaaf: require('../assets/audio/letters/qaaf.m4a'),
  kaaf: require('../assets/audio/letters/kaaf.m4a'),
  meem: require('../assets/audio/letters/meem.m4a'),
  s_haa: require('../assets/audio/letters/s_haa.m4a'),
  hamzah: require('../assets/audio/letters/hamzah.m4a'),


  //Ummumi Mashq
  bism: require('../assets/audio/murakkabat/umumi/baa_seen_meem.m4a'),
  mulk: require('../assets/audio/murakkabat/umumi/meem_laam_kaaf.m4a'),
  yakan: require('../assets/audio/murakkabat/umumi/yaa_kaaf_noon.m4a'),
  ahl: require('../assets/audio/murakkabat/umumi/alif_laam_meem.m4a'),
  kutub: require('../assets/audio/murakkabat/umumi/kaaf_taa_baa.m4a'),
  baad: require('../assets/audio/murakkabat/umumi/baa_ain_daal.m4a'),
  khabar: require('../assets/audio/murakkabat/umumi/khaun_ya_ro.m4a'),
  jannat: require('../assets/audio/murakkabat/umumi/jeem_noon_ta.m4a'),
  adan: require('../assets/audio/murakkabat/umumi/ain_daal_noon.m4a'),
  razi: require('../assets/audio/murakkabat/umumi/ro_daud_ya.m4a'),
  khashyat: require('../assets/audio/murakkabat/umumi/khaun_sheen_ya.m4a'),
  // sabat: require('../assets/audio/murakkabat/umumi/sad_baa_taa.m4a'),
  kasb: require('../assets/audio/murakkabat/umumi/kaaf_seen_baa.m4a'),
  habl: require('../assets/audio/murakkabat/umumi/haa_baa_laam.m4a'),
  nasr: require('../assets/audio/murakkabat/umumi/noon_saud_ro.m4a'),

  fath: require('../assets/audio/murakkabat/umumi/fa_taa_haa.m4a'),
  ribat: require('../assets/audio/murakkabat/umumi/ro_baa_kaaf.m4a'),
  deen: require('../assets/audio/murakkabat/umumi/daal_ya_noon.m4a'),
  saif: require('../assets/audio/murakkabat/umumi/saud_ya_fa.m4a'),
  bait: require('../assets/audio/murakkabat/umumi/baa_ya_taa.m4a'),

  joo: require('../assets/audio/murakkabat/umumi/jeem_wow_ain.m4a'),
  khauf: require('../assets/audio/murakkabat/umumi/khaun_wow_faa.m4a'),
  alam: require('../assets/audio/murakkabat/umumi/alif_laam_meem.m4a'),
  kaif: require('../assets/audio/murakkabat/umumi/kaaf_yaa_faa.m4a'),
  faal: require('../assets/audio/murakkabat/umumi/faa_ain_laam.m4a'),

  feel: require('../assets/audio/murakkabat/umumi/faa_ya_laam.m4a'),
  tayr: require('../assets/audio/murakkabat/umumi/taun_ya_ro.m4a'),
  jam: require('../assets/audio/murakkabat/umumi/jeem_meem_ain.m4a'),
  amad: require('../assets/audio/murakkabat/umumi/ain_meem_daal.m4a'),
  asr: require('../assets/audio/murakkabat/umumi/ain_saud_ro.m4a'),
  khasr: require('../assets/audio/murakkabat/umumi/khaun_seen_ro.m4a'),
  sabr: require('../assets/audio/murakkabat/umumi/saud_baa_ro.m4a'),
  sauf: require('../assets/audio/murakkabat/umumi/seen_wow_fa.m4a'),
  ilm: require('../assets/audio/murakkabat/umumi/ain_laam_meem.m4a'),
  // ain: require('../assets/audio/murakkabat/umumi/ain.m4a'),
  kitaab: require('../assets/audio/murakkabat/umumi/kaaf_taa_alif_baa.m4a'),
  bayyinah: require('../assets/audio/murakkabat/umumi/baa_yaa_noon_taa.m4a'),
  qeemah: require('../assets/audio/murakkabat/umumi/kauf_yaa_meem_taa.m4a'),
  tafarruq: require('../assets/audio/murakkabat/umumi/taa_faa_ro_kauf.m4a'),
  salat: require('../assets/audio/murakkabat/umumi/saud_laam_wow_taa.m4a'),

  zakah: require('../assets/audio/murakkabat/umumi/zaa_kaaf_wow_taa.m4a'),
  tajri: require('../assets/audio/murakkabat/umumi/taa_jeem_ro_ya.m4a'),
  aoodhu: require('../assets/audio/murakkabat/umumi/alif_ain_wow_zaal.m4a'),
  nafathat: require('../assets/audio/murakkabat/umumi/noon_faa_saa_taa.m4a'),
  aabud: require('../assets/audio/murakkabat/umumi/alif_ain_baa_daal.m4a'),

  sayasla: require('../assets/audio/murakkabat/umumi/seen_ya_saud_laam_ya.m4a'),
  tadleel: require('../assets/audio/murakkabat/umumi/taa_daud_laam_yaa_laam.m4a'),
  aatainak: require('../assets/audio/murakkabat/umumi/alif_ain_tau_yaa_noon_kaaf.m4a'),
  aalameen: require('../assets/audio/murakkabat/umumi/alif_laam_ain_laam_meem_yaa_noon.m4a'),
  nastaeen: require('../assets/audio/murakkabat/umumi/noon_seen_taa_ain_yaa_noon.m4a'),
  mustaqeem: require('../assets/audio/murakkabat/umumi/meem_seen_taa_kauf_yaa_meem.m4a'),
  maghdoob: require('../assets/audio/murakkabat/umumi/meem_gain_daud_wow_baa.m4a'),
  munfakkeen: require('../assets/audio/murakkabat/umumi/meem_noon_faa_kaaf_yaa_noon.m4a'),
  lilmusalleen: require('../assets/audio/murakkabat/umumi/laam_laam_meem_saud_laam_yaa_noon.m4a'),
  astaghfir: require('../assets/audio/murakkabat/umumi/alif_seen_taa_gain_faa_ro_haa.m4a'),


  munaji: require('../assets/audio/murakkabat/filasma/meem_yaa_alif_jeem_yaa.m4a'),
  noor: require('../assets/audio/murakkabat/filasma/noon_wow_ro.m4a'),
  muhammad: require('../assets/audio/murakkabat/filasma/meem_haa_meem_daal.m4a'),
  sahib: require('../assets/audio/murakkabat/filasma/saud_alif_haa_baa.m4a'),
  //haji: require('../assets/audio/murakkabat/filasma/haa_jeem_yaa.m4a'),
  imdad: require('../assets/audio/murakkabat/filasma/alif_meem_daal_alif_daal.m4a'),
  allah: require('../assets/audio/murakkabat/filasma/alif_laam_laam_haa.m4a'),
  muhaddith: require('../assets/audio/murakkabat/filasma/meem_haa_daal_saa.m4a'),
  makki: require('../assets/audio/murakkabat/filasma/meem_kaaf_yaa.m4a'),
  imam: require('../assets/audio/murakkabat/filasma/alif_meem_alif_meem.m4a'),
  rashid: require('../assets/audio/murakkabat/filasma/ro_sheen_yaa_daal.m4a'),
  //ibrat: require('../assets/audio/murakkabat/filasma/ain_baa_raa_taa.m4a'),
  khaleel: require('../assets/audio/murakkabat/filasma/khaun_laam_yaa_laam.m4a'),
  shaikh: require('../assets/audio/murakkabat/filasma/sheen_yaa_khaun.m4a'),
  zakariya: require('../assets/audio/murakkabat/filasma/zaa_kaaf_ro_yaa_alif.m4a'),

  faqeeh: require('../assets/audio/murakkabat/filasma/faa_kauf_yaa_haa.m4a'),
  hamood: require('../assets/audio/murakkabat/filasma/meem_haa_meem_wow_daal.m4a'),
  murshid: require('../assets/audio/murakkabat/filasma/meem_ra_sheen_daal.m4a'),
  mahmood: require('../assets/audio/murakkabat/filasma/meem_ha_meem_waow_daal.m4a'),
  mufti: require('../assets/audio/murakkabat/filasma/meem_fa_ta_ya.m4a'),
  mafakkir: require('../assets/audio/murakkabat/filasma/meem_fa_kaaf_ra.m4a'),
  khanfuri: require('../assets/audio/murakkabat/filasma/kha_alif_noon_fa_waow_ra_ya.m4a'),
  ahmad: require('../assets/audio/murakkabat/filasma/alif_ha_meem_daal.m4a'),
  ummat: require('../assets/audio/murakkabat/filasma/alif_meem_ta.m4a'),
  mujaddid: require('../assets/audio/murakkabat/filasma/meem_jeem_daal_daal.m4a'),
  hafizji: require('../assets/audio/murakkabat/filasma/ha_alif_fa_zau_jeem_yaa.m4a'),
  makatib: require('../assets/audio/murakkabat/filasma/meem_kaaf_alif_ta_ba.m4a'),
  yusuf: require('../assets/audio/murakkabat/filasma/ya_wao_seen_fa.m4a'),
  kafordra: require('../assets/audio/murakkabat/filasma/kaaf_alif_fa_waow_daal_ra_alif.m4a'),
  ismaeel: require('../assets/audio/murakkabat/filasma/alif_seen_meem_ain_ya_laam.m4a'),
  sadiq: require('../assets/audio/murakkabat/filasma/saud_daal_ya_qaf.m4a'),
  nasir: require('../assets/audio/murakkabat/filasma/nun_alif_saad_ra.m4a'),
  siddiq: require('../assets/audio/murakkabat/filasma/saud_daal_ya_qaf.m4a'),
  aljauf: require('../assets/audio/murakkabat/filasma/alif_laam_ta_alif_fa.m4a'),
  aziz: require('../assets/audio/murakkabat/filasma/ain_za_ya_za.m4a'),
  anwar: require('../assets/audio/murakkabat/filasma/alif_nun_waow_ra.m4a'),
  shakeel: require('../assets/audio/murakkabat/filasma/sheen_kaam_ya_laam.m4a'),
  salim: require('../assets/audio/murakkabat/filasma/seen_lam_ya_meem.m4a'),
  tauseef: require('../assets/audio/murakkabat/filasma/ta_waow_saud_ya_fa.m4a'),
  bilal: require('../assets/audio/murakkabat/filasma/ba_laam_alif_laam.m4a'),
  noorani: require('../assets/audio/murakkabat/filasma/nun_wao_ra_alif_nun_ya.m4a'),
  imran: require('../assets/audio/murakkabat/filasma/ain_meem_ra_alif_nun.m4a'),
  bardoli: require('../assets/audio/murakkabat/filasma/ba_alif_ra_daal_waow_laam_ya.m4a'),
  daral: require('../assets/audio/murakkabat/filasma/daal_alif_ra_alif_laam.m4a'),
  surat: require('../assets/audio/murakkabat/filasma/seen_waow_ra_ta.m4a'),
  fujarat: require('../assets/audio/murakkabat/filasma/gain_jeem_ra_alif_ta.m4a'),
  alhind: require('../assets/audio/murakkabat/filasma/alif_laam_ha_nun_daal.m4a'),

} as const;

export type LetterAudioKey = keyof typeof lettersAudio;
